apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "github-portfolio.fullname" . }}
  labels:
    {{- include "github-portfolio.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "github-portfolio.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "github-portfolio.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "github-portfolio.fullname" . }}
      containers:
        - name: {{ include "github-portfolio.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: {{ include "github-portfolio.fullname" . }}-config
          env:
            - name: VITE_GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ include "github-portfolio.fullname" . }}-secret
                  key: VITE_GITHUB_TOKEN
                  optional: true
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 5
