{{- if and .Values.secret.enabled .Values.secret.viteGithubToken -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-portfolio.fullname" . }}-secret
  labels:
    {{- include "github-portfolio.labels" . | nindent 4 }}
type: Opaque
stringData:
  VITE_GITHUB_TOKEN: {{ .Values.secret.viteGithubToken | quote }}
{{- end -}}
