{{- if .Values.secret.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "github-portfolio.fullname" . }}-secret
  labels:
    app.kubernetes.io/name: {{ include "github-portfolio.name" . }}
    helm.sh/chart: {{ include "github-portfolio.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Service }}
type: Opaque
data:
  {{- if .Values.secret.viteGithubToken }}
  VITE_GITHUB_TOKEN: {{ .Values.secret.viteGithubToken | b64enc }}
  {{- else }}
  VITE_GITHUB_TOKEN: ""
  {{- end }}
{{- end -}}
