apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "github-portfolio.fullname" . }}
  labels:
    {{- include "github-portfolio.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "github-portfolio.fullname" . }}
  labels:
    {{- include "github-portfolio.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "github-portfolio.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
