apiVersion: v1
kind: ServiceAccount
metadata:
  name: github-portfolio-sa
  namespace: github-portfolio
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-portfolio-binding
  namespace: github-portfolio
subjects:
- kind: ServiceAccount
  name: github-portfolio-sa
  namespace: github-portfolio
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: view
