name: GitOps CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

jobs:
  update-gitops:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: ./.github/workflows/reuseable-gitops-update.yml
    with:
      helm_values_path: "helm/github-portfolio/values.yaml"
      image_tag: ${{ github.event.workflow_run.head_sha }}
    secrets:
      git_token: ${{ secrets.GITHUB_TOKEN }}
