name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - name: Install Dependencies & Run Tests
        run: |
          npm ci
          npm test -- --coverage --coverage.reporter=lcov --reporter=default --reporter=junit --outputFile=test-report.xml

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-report
          path: test-report.xml

      - name: Run npm audit
        run: npm audit --audit-level=CRITICAL

      - name: Snyk Scan
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        if: ${{ env.SNYK_TOKEN != '' }}
        uses: snyk/actions/node@master

  build-and-push:
    needs: test-and-audit
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/reusable-docker-build.yml
    with:
      image_name: "akashkoche/github-portfolio"
    secrets:
      registry_username: ${{ secrets.DOCKERHUB_USERNAME }}
      registry_password: ${{ secrets.DOCKERHUB_TOKEN }}
      cosign_private_key: ${{ secrets.COSIGN_PRIVATE }}
      cosign_password: ${{ secrets.COSIGN_PASSWORD }}
